name: Application Form
description: Fill out this application form to apply for membership
assignees:
  - rdp-studio
body:
  - type: markdown
    attributes:
      value: |
        Tip: Please fill in your GitHub user name and a brief overview of your application in the title.
  - type: input
    id: name
    attributes:
      label: Your GitHub username
      description: Required for membership invite and preventing bots
      placeholder: ex. rdp-studio
    validations:
      required: true
  - type: input
    id: why
    attributes:
      label: Why do you want to join this community
      description: Required for membership validation and preventing bots
      placeholder: ex. Learn and share my development experience
    validations:
      required: true
  - type: checkboxes
    id: checkagain
    attributes:
      label: Checkout these
      description: |
        1. I will not disclose the internal content in this community.
        2. I will inject new vitality into this community.
        3. I abide by the laws of the people's Republic of China and your local place.
        4. I abide by other rules of this community, such as forum rules.
      options:
        - label: I confirm to abide by the above terms
          required: true
